### ISSUE TITLE
Assets Not Showing on build

### ISSUE THREAD

**Issue by AmGarera** [rtCamp/VueTheme#23]
As the title says it's not showing assets that get bundled upon running npm run build. Any advice here?

**Comment by sagarkbhatt** [comment]
Hi @AmGarera 
I am not sure how you are using assets in this theme. Can you tell me more about that or show me directory structure?
FYI this theme is not ready for production. This is an experimental Vue + WP theme project. 

Thanks

**Comment by AmGarera** [comment]
Fixed, no worries!
