### ISSUE TITLE
Dev Enviroment

### ISSUE THREAD

**Issue by juanpprieto** [rtCamp/VueTheme#32]
Hey guys, 

Thanks for the theme! - I'm trying to get the dev environment to work but I'm having issues.

Whenever I make changes to any of the Vue components it doesn't seem to update the theme. 

Can you elaborate how is you environment setup? Nginx locally via vagrant? Ideally I would love to work on a remote nginx dev enviroment. Easyengine + Digital Ocean.

Thanks

**Comment by sagarkbhatt** [comment]
@juanpprieto 
We are using webpack as build tool so you have to generate new build each time you update component.

For Dev environment setup with webpack HMR. you need to follow below steps.

1 . Define `RT_VUE_DEV` in wp-config.php.
2. Execute `npm run dev` command.
3. Get the url generated from console. Typically it would be `localhost:port`.
4. Paste it in functions.php line - 12.

Snippet : `wp_enqueue_script( 'rest-theme-vue', 'http://localhost:8080/dist/build.js', array( 'jquery' ), '1.0.0', true );`

This will enable Webpack HMR in your local/remote environment. So you don't have to generate production build every time you made changes to component.

For production ready build you can simply execute `npm run build` command.
