### ISSUE TITLE
Npm run dev

### ISSUE THREAD

**Issue by zexingguo** [rtCamp/VueTheme#33]
I clone this repo in my wp-content/theme and npm run dev doesn't work at all.

**Comment by sagarkbhatt** [comment]
@zexingguo Can you give more detail ?

**Comment by zexingguo** [comment]
Okay, the vue-theme works fine with the mamp server with production ver. I was expecting to have a local vue version that run by webpack so I dont have to do `npm run build` every time to see my changes. `npm run dev` cannot get / which is the index.php I'm guessing. 

Sorry for the poor explanation if it doesn't make sense.

**Comment by sagarkbhatt** [comment]
@zexingguo 

Can you check my answer in https://github.com/rtCamp/VueTheme/issues/32 ?

Let me know if that works for you or not.

**Comment by zexingguo** [comment]
@sagarkbhatt 

That definitely solve my issue !!!!! 

Thanks for the response, I really appreciated it !
